spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdatabase
    username: postgres
    password: auspicious04
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true